### ISSUE TITLE
Audio Streaming Integration

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#45]
Create a new Spark streaming connector that opens a long-living streaming connection to a configurable list of radio streaming services. This connector should perform Cognitive Services Speech-To-Text conversion off the audio stream and feeds the data through the sentiment, topical and location feature extractors.

**Comment by c-w** [comment]
There are a few parts to this task:

1) Create a Scala library that implements the [Cognitive Services Speech Protocol](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/websocketprotocol). This is useful in its own right so it should be general purpose and independently deployable.
2) Create a Spark Streaming connector that ingests radio streams. We'll have to deal with multiple input formats as some radio streams are published in mp3, [pls](https://en.wikipedia.org/wiki/PLS_(file_format)), ogg, etc.
3) Convert the radio streams to wav, plug the wav into the speech-to-text service and plug the converted text into Fortis.

**Comment by c-w** [comment]
There aren't many great websocket client libraries for Scala, so I'm implementing the Cognitive Services Speech Protocol in Java, in the [SpeechToText-WebSockets-Java](https://github.com/CatalystCode/SpeechToText-WebSockets-Java) repository.

**Comment by c-w** [comment]
Finally managed to figure out how to set up the connection. The API documentation is lacking in some parts:

1) The target endpoints are in the format /speech/**recognition**/interactive/cognitiveservices/v1, not *recognize* as stated by the [docs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/bingvoicerecognition#endpoints).
2) The speech.config message needs the X-RequestId header even though the [docs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/websocketprotocol#required-message-headers-2) state that it shouldn't be included.
3) It's necessary to include additional parameters in the websocket request URL. These are not mentioned in the websocket docs but in the REST docs: [format](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/bingvoicerecognition#output-format) and [language](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/bingvoicerecognition#recognition-languages).
4) What the [docs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/websocketprotocol#authorization) call an authorization header is actually a query parameter on the websocket URL. Furthermore, instead of the authorization header, we can also use the `Ocp-Apim-Subscription-Key` like on most Cognitive Services but this is undocumented.

**Comment by c-w** [comment]
Initial implementation now works.

**Comment by c-w** [comment]
Library is now up on Maven: [speechtotext-websockets-java](https://search.maven.org/#artifactdetails%7Ccom.github.catalystcode%7Cspeechtotext-websockets-java%7C0.0.1%7Cjar).

**Comment by c-w** [comment]
MP3-to-PCM conversion seems a bit tricky. The Java eco-system isn't great here. Added some extensibility points to [jlayer](http://www.javazoom.net/javalayer/javalayer.html) to offer stream-based conversion, but the performance is quite slow. Andrei Ermilov's team just built a MP3 decoder and were thinking about releasing a Java wrapper. Let's see what that gets us. Alternatively, [xuggler](http://www.xuggle.com/xuggler/) seems a popular library for MP3 decoding, but we'd have to make our own build as the pre-built sources are GPL licensed.

**Comment by c-w** [comment]
For now I implemented the following approach for adding support for transcription of mp3s (released in version [0.0.4](https://search.maven.org/#artifactdetails%7Ccom.github.catalystcode%7Cspeechtotext-websockets-java%7C0.0.4%7Cjar)):
1. Read chunks from the mp3 stream until we have 256kb.
2. Write the mp3 to disk.
3. Use jlayer to convert the mp3 file to a wav file.
4. Stream the wav file to the transcription service via the websocket.

Ideally, we wouldn't need the trip to the disk, but it's the least hassle way to make the MP3-to-PCM conversion work for now.

**Comment by c-w** [comment]
PR for the integration with project-fortis-spark: [#8](https://github.com/CatalystCode/project-fortis-spark/pull/8)

**Comment by c-w** [comment]
PR merged which adds radio streaming integration to Fortis. Any further enhancements (e.g. deal with bad audio, deal with end-of-audio-detection from cognitive services) will come as separate tasks, likely on the [SpeechToText-WebSockets-Java](https://github.com/CatalystCode/SpeechToText-WebSockets-Java) repo.
